---
services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE=sebastienelet/docker-ubuntu1404-ansible DOCKER_INIT=/sbin/init ROLE_OPTIONS="nodejs_version=4.x"
    - DOCKER_IMAGE=sebastienelet/docker-ubuntu1404-ansible DOCKER_INIT=/sbin/init ROLE_OPTIONS="nodejs_version=6.x"
    - DOCKER_IMAGE=sebastienelet/docker-ubuntu1404-ansible DOCKER_INIT=/sbin/init ROLE_OPTIONS="nodejs_version=8.x"

before_install:
  - make docker-pull

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
