---
- name: add nodejs GPG key into apt
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  tags:
  - nodejs

- name: add nodejs repository
  apt_repository:
    repo: "deb http://deb.nodesource.com/node_{{nodejs_version}} {{ansible_distribution_release}} main"
    state: present
    update_cache: yes
  tags:
  - nodejs

- name: install nodejs package
  apt:
    pkg: nodejs
    state: present
  tags:
  - nodejs
