---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - python-pycurl
  tags:
  - nodejs

- name: add nodejs GPG key into apt
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  tags:
  - nodejs

- name: add nodejs repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{nodejs_version}} wheezy main"
    state: present
  register: nodejs_repo_added
  tags:
  - nodejs

- name: apt update cache
  apt:
    update_cache: yes
  when: nodejs_repo_added.changed
  tags:
  - nodejs

- name: install nodejs package
  apt:
    pkg: nodejs
    state: present
  tags:
  - nodejs
